swaps/urls.py
from django.conf.urls.defaults import *

from swaps import views, models
from swaps.forms import *


urlpatterns = patterns('',
    # offer
    url(r'^offer/(?P<offer_id>\d+)/$', 'swaps.views.offer', name='offer'),
    
    # all offers
    url(r'^$', 'swaps.views.offers', name="offer_list_all"),
       
    # your offers
    url(r'^your_offers/$', 'swaps.views.your_offers', name='offer_list_yours'),
    
    # swap
    url(r'^swap/(?P<swap_id>\d+)/$', 'swaps.views.swap', name='swap'),
    
    # swaps proposed_to_you
    url(r'^proposed_to_you/$', 'swaps.views.proposed_to_you', name='proposed_to_you'),
    
    # swaps proposed_by_you
    url(r'^proposed_by_you/$', 'swaps.views.proposed_by_you', name='proposed_by_you'),
    
    # your accepted swaps
    url(r'^accepted/$', 'swaps.views.accepted_swaps', name='accepted_swaps'),
    
    # your dead swaps
    url(r'^dead/$', 'swaps.views.dead_swaps', name='dead_swaps'),
    
    # new offer
    url(r'^new/$', 'swaps.views.new', name='offer_new'),
    
    # edit offer
    url(r'^edit/(?P<offer_id>\d+)/$', 'swaps.views.edit_offer', name='offer_edit'),
    
    # cancel offer
    url(r'^cancel/(?P<offer_id>\d+)/$', 'swaps.views.cancel_offer', name='offer_cancel'),
    
    # delete offer
    url(r'^delete/(?P<offer_id>\d+)/$', 'swaps.views.delete_offer', name='offer_delete'),
    
    # propose swap
    url(r'^proposal/(?P<offer_id>\d+)/$', 'swaps.views.propose_swap', name='propose_swap'),
    
    # accept swap
    url(r'^accept/(?P<swap_id>\d+)/$', 'swaps.views.accept_swap', name='accept_swap'),
    
    # reject swap
    url(r'^reject/(?P<swap_id>\d+)/$', 'swaps.views.reject_swap', name='reject_swap'),
    
    # cancel swap
    url(r'^cancel/(?P<swap_id>\d+)/$', 'swaps.views.cancel_swap', name='cancel_swap'),


    # ajax validation
    #(r'^validate/$', 'ajax_validation.views.validate', {'form_class': BlogForm, 'callback': lambda request, *args, **kwargs: {'user': request.user}}, 'blog_form_validate'),
)

swaps/models.py
from datetime import datetime

from django.db import models
from django.db.models import signals
from django.contrib.auth.models import User
from django.db import transaction
from django.utils.translation import ugettext_lazy as _
from django.conf import settings

from tagging.fields import TagField
from tagging.models import Tag

if "notification" in settings.INSTALLED_APPS:
    from notification import models as notification
else:
    notification = None

class Offer(models.Model):
    
    """An offer to swap something between users
    
    An offer optionally includes what the offerer wants in exchange.
    
    Once an offer reaches the proposed state (proposes a swap), 
    it cannot be included in any other swaps.  However,
    an offer may be included as the responding offer 
    in many swaps.
    
    Once an offer reaches the swapped state,
    nothing can be changed except moving the state to fulfilled.
    The fulfilled state is optional.
    
    """
    
    STATE_CHOICES = (
        (1, _('offered')),
        (2, _('proposed')), # is the proposing offer of a proposed swap
        (3, _('swapped')), # is included in an accepted swap
        (4, _('fulfilled')), # the offering has been delivered
        (5, _('canceled')), # the offer has been canceled
    )
    
    offerer = models.ForeignKey(User, verbose_name=_('offerer'))
    short_description = models.CharField(_('short description'), max_length=64)
    offering = models.TextField(_('offering'))
    want = models.TextField(_('want'), blank=True, null=True)
    state = models.PositiveSmallIntegerField(_('state'), max_length="1", choices=STATE_CHOICES, default=1)
    offered_time = models.DateTimeField(_('offered time'), default=datetime.now)
    swapped_by = models.ForeignKey('Swap', blank=True, null=True, verbose_name=_('swapped by'))
    tags = TagField()
    
    def __unicode__(self):
        return self.short_description
    
    def get_absolute_url(self):
        return ('offer', [self.id])
    get_absolute_url = models.permalink(get_absolute_url)
    
    def is_changeable(self):
        
        """ If state is swapped, can only change state to fulfilled.
        
        If state is fulfilled, no changes allowed at all.
        
        """
        
        if int(self.state) > 2:
            return False
        else:
            return True
        
    def is_cancelable(self):
        answer = True
        if self.proposed_swaps.filter(state__lte=3):
            answer = False
        elif self.responding_swaps.filter(state__lte=3):
            answer = False
        return answer
    
    def cancel(self):
        if self.is_cancelable():
            self.state = 5
            self.save()
    
    def is_deletable(self):
        answer = True
        if self.proposed_swaps.all():
            answer = False
        elif self.responding_swaps.all():
            answer = False
        return answer
        
    def propose(self):
        if self.is_changeable():
            self.state = 2
            self.save()
            
    def swap(self, swap):
        """
        This method cannot save.
        Called from Swap, must be covered by Swap transaction.    
        """
        
        if self.is_changeable():
            self.state = 3
            self.swapped_by = swap
            #self.save()
            
    def fulfill(self):
        """ This method assumes that fulfillment starts at offers """
        if int(self.state) == 3:
            self.state = 4
            self.save()
            self.swapped_by.offer_fulfilled()
            
    def is_fulfilled(self):
        return self.state == 4
            
    def revert(self):
        """        
        This method cannot save.
        Called from Swap, must be covered by Swap transaction.            
        """
        
        if self.is_changeable():
            self.state = 1
            #self.save()
            
    def proposed_swap(self):
        if self.proposed_swaps.all():
            return self.proposed_swaps.all()[0]
        else:
            return None


class Swap(models.Model):
    
    """An exchange of anything between offers.
    
    When a swap is accepted, the state of both offers is changed to swapped.
    Any other swaps involving either of the accepted offers must be changed
    to the conflicted state.  In that state, the swap is effectively dead.
    
    If the swap is rejected or canceled, the state of both offers is changed
    back to offered.
    
    The fulfilled state is optional.
    
    Note:  at this stage, swaps can only include 2 offers.
    That may prove to be too restrictive, but it's simple.
    
    """
    
    STATE_CHOICES = (
        (1, _('proposed')), # proposed by the proposing offer
        (2, _('accepted')), # the responding offer has accepted the swap
        (3, _('fulfilled')), # all offers have been delivered
        (4, _('rejected')), # the responding offer has rejected the swap
        (5, _('canceled')), # the proposing offer has canceled the swap
        (6, _('conflicted')), # another swap took one of these offers
    )
    
    proposing_offer = models.ForeignKey(Offer, related_name='proposed_swaps', verbose_name=_('proposing offer'))
    responding_offer = models.ForeignKey(Offer, related_name='responding_swaps', verbose_name=_('responding offer'))
    state = models.PositiveSmallIntegerField(_('state'), max_length="1", choices=STATE_CHOICES, default=1)
    proposed_time = models.DateTimeField(_('proposed time'), default=datetime.now)
    accepted_time = models.DateTimeField(_('accepted time'), blank=True, null=True)
    fulfilled_time = models.DateTimeField(_('fulfilled time'), blank=True, null=True)
    killed_time = models.DateTimeField(_('killed time'), blank=True, null=True)
    conflicted_by = models.ForeignKey('self', blank=True, null=True, related_name='conflicting_swap', verbose_name=_('conflicted by'))
    
    def __unicode__(self):
        return _('Proposing offer: %(proposing_offer)s, Responding offer %(responding_offer)s') % {
            'proposing_offer': self.proposing_offer.short_description,
            'responding_offer': self.responding_offer.short_description,
        }
        
    def get_absolute_url(self):
        return ('swap', [self.id])
    get_absolute_url = models.permalink(get_absolute_url)

        
    def swap_offers(self):
        self.proposing_offer.swap(self)
        self.responding_offer.swap(self)
        
    def revert_offers(self):
        self.proposing_offer.revert()
        self.responding_offer.revert()
        
    def accept(self):
        self.state = 2
        self.swap_offers()
        self.accepted_time = datetime.now()
        
    def fulfill(self):
        self.state = 3
        self.fulfilled_time = datetime.now()
        self.save()
        
    def offer_fulfilled(self):
        if self.proposing_offer.is_fulfilled() and self.responding_offer.is_fulfilled():
            self.fulfill()
           
    def reject(self):
        self.state = 4
        self.killed_time = datetime.now()
        self.revert_offers()
        
    def cancel(self):
        self.state = 5
        self.killed_time = datetime.now()
        self.revert_offers()
        
    def conflict(self, conflicting_swap):
        self.state = 6
        self.conflicted_by = conflicting_swap
        self.killed_time = datetime.now()
        self.revert_offers()
        if notification:
            notification.send([self.proposing_offer.offerer,], "swaps_conflict", 
                {"losing_swap": self, 
                 "winning_swap": conflicting_swap})
            notification.send([self.responding_offer.offerer,], "swaps_conflict", 
                {"losing_swap": self, 
                 "winning_swap": conflicting_swap})
              
    @transaction.commit_manually
    def save(self, force_insert=False, force_update=False):
        
        """ Enforce state change rules...
        
        and watch out for conflicting swaps.
        First swap to get to accepted state wins,
        all competing swaps' states set to conflicted.
        This swap might be the winner or the loser.
        
        """

        try:
            changeable = False 
            
            if self.pk:
                previous_state = Swap.objects.get(pk=self.pk).state
                if self.state != previous_state:
                    if int(self.state) == 6:
                        changeable = True
                    elif int(previous_state) == 1:
                        changeable = True
                        if int(self.state) == 2:
                            competing_swaps = list(self.proposing_offer.proposed_swaps.all())
                            competing_swaps.extend(list(self.proposing_offer.responding_swaps.all()))
                            competing_swaps.extend(list(self.responding_offer.proposed_swaps.all()))
                            competing_swaps.extend(list(self.responding_offer.responding_swaps.all()))
                            for swap in competing_swaps:
                                if swap.pk != self.pk:
                                    if swap.state == 2: # this swap loses a conflict
                                        self.conflict(swap)
            else:
                changeable = True
                
            if changeable: 
                super(Swap, self).save(force_insert, force_update)
                # swap offers usually changed when swap changes
                # must be covered in same transaction
                self.proposing_offer.save()
                self.responding_offer.save()
                if int(self.state) == 1:
                    self.proposing_offer.propose()
                elif int(self.state) == 2:
                    for swap in competing_swaps: # this swap wins any conflicts
                        if swap.pk != self.pk:
                            swap.conflict(self)
                            swap.save()

swaps/templates/swaps/accepted.html
{% extends "swaps/base.html" %}

{% load i18n %}
{% load pagination_tags %}
{% load shorttimesince_tag %}

{% block head_title %}{% blocktrans %}Your accepted Swaps{% endblocktrans %}{% endblock %}

{% block body %}
    
    <h1>{% trans "Your accepted Swaps" %}</h1>
    
    
    {% if swaps %}

        
        {% autopaginate swaps %}

			<table class="tasks" >
				<tr>
					<th>Accepted Time</th>
					<th>Proposing Offer</th>
					<th>Offered By</th>
					<th>Responding Offer</th>
					<th>Offered By</th>
					<th>State</th>
				</tr>
				{% for swap in swaps %}
					<tr class="{% cycle odd,even %}">
						<td><a href="{{ swap.get_absolute_url }}">{{ swap.accepted_time|shorttimesince }}</a></td>
						<td>{{ swap.proposing_offer }}</td>
						<td>{{ swap.proposing_offer.offerer }}</td>
						<td>{{ swap.responding_offer }}</td>
						<td>{{ swap.responding_offer.offerer }}</td>
						<td>{{ swap.get_state_display }}</td>
					</tr>
				{% endfor %}
			</table>

        {% paginate %}

    {% else %}
        No accepted swaps yet.
    {% endif %}
    
{% endblock %}

swaps/templates/swaps/base.html
{% extends "site_base.html" %}

{% load i18n %}

{% block rtab_id %}id="swaps_tab"{% endblock %}

{% block subnav %}
    {% if user.is_authenticated %}
        <ul>
            <li><a href="{% url offer_list_all %} ">{% trans "Open Offers" %}</a></li>
            <li><a href="{% url offer_list_yours %}">{% trans "Your Offers" %}</a></li>
			<li><a href="{% url offer_new %}">{% trans "Make an Offer" %}</a></li>
			<li><a href="{% url proposed_to_you %}">{% trans "Proposed to you" %}</a></li>
			<li><a href="{% url proposed_by_you %}">{% trans "Proposed by you" %}</a></li>
            <li><a href="{% url accepted_swaps %}">{% trans "Accepted" %}</a></li>
			<li><a href="{% url dead_swaps %}">{% trans "Dead" %}</a></li>
        </ul>
    {% else %}
        &nbsp;
    {% endif %}
{% endblock %}

swaps/templates/swaps/dead.html
{% extends "swaps/base.html" %}

{% load i18n %}
{% load pagination_tags %}
{% load shorttimesince_tag %}

{% block head_title %}{% blocktrans %}Your dead Swaps{% endblocktrans %}{% endblock %}

{% block body %}
    
    <h1>{% trans "Your dead Swaps" %}</h1>
    
    
    {% if swaps %}

        
        {% autopaginate swaps %}

			<table class="tasks" >
				<tr>
					<th>Time of death</th>
					<th>Proposing Offer</th>
					<th>Offered By</th>
					<th>Responding Offer</th>
					<th>Offered By</th>
					<th>State</th>
					<th>Conflict</th>
				</tr>
				{% for swap in swaps %}
					<tr class="{% cycle odd,even %}">
						<td><a href="{{ swap.get_absolute_url }}">{{ swap.killed_time|shorttimesince }}</a></td>
						<td>{{ swap.proposing_offer }}</td>
						<td>{{ swap.proposing_offer.offerer }}</td>
						<td>{{ swap.responding_offer }}</td>
						<td>{{ swap.responding_offer.offerer }}</td>
						<td>{{ swap.get_state_display }}</td>
						<td>
							{%if swap.conflicted_by %}
								<a href="{{ swap.conflicted_by.get_absolute_url }}">{{ swap.conflicted_by }}</a>
							{% else %}
								&nbsp;
							{% endif %}
						</td>
					</tr>
				{% endfor %}
			</table>

        {% paginate %}

    {% else %}
        No dead swaps yet.
    {% endif %}
    
{% endblock %}

swaps/templates/swaps/edit_offer.html
{% extends "swaps/base.html" %}

{% load i18n %}
{% load tagging_tags %}

{% block head_title %}{% blocktrans %}Editing Offer{% endblocktrans %}{% endblock %}

{% block body %}
    
    <h1>{% trans "Editing Offer" %}</h1>
    
    {% ifequal offer.offerer request.user %}
        <div>
            <form id="offer_form" method="POST" action="">
                <table>
                    {{ offer_form }}
                    <tr><td></td><td><input type="hidden" name="action" value="update" /><input type="submit" value="{% trans "update" %}"/></td></tr>
                </table>
            </form>
        </div>
    {% else %}
        <p>You are not the creator of this offer.</p>
    {% endifequal %}
{% endblock %}

swaps/templates/swaps/new_offer.html
{% extends "swaps/base.html" %}

{% load i18n %}

{% block head_title %}{% blocktrans %}Add a new Offer{% endblocktrans %}{% endblock %}

{% block body %}
    
    <h1>{% trans "Add a new Offer" %}</h1>
    
    <form id="offer_form" method="POST" action="">
        <table>
            {{ offer_form }}
            <tr><td></td><td><input type="hidden" name="action" value="create" /><input type="submit" value="create"/></td></tr>
        </table>
    </form>

{% endblock %}

swaps/templates/swaps/offer.html
{% extends "swaps/base.html" %}

{% load i18n %}
{% load threadedcommentstags %}
{% load tagging_tags %}

{% block head_title %}{% blocktrans %}Offer{% endblocktrans %} : {{ offer.short_description }}{% endblock %}


{% block body %}
    
    <div class="blog-post">
        <h2>{{ offer.short_description }}</h2>
        <div class="blog-meta"><p>Offered by: <a href="{% url profiles.views.profile offer.offerer.username %}">{{ offer.offerer.username }}</a> on {{ offer.offered_time|date }}</p></div>
        <p>
			Offering: {{ offer.offering|urlize }}
		</p>
		<p>
			Want: {{ offer.want|urlize }}
		</p>
		<p>
			State: {{ offer.get_state_display }}
		</p>
		<div class="blog-tags">
            <p><img src="/site_media/tags.png" border="0" class="noborder" align="absmiddle" />
            {% tags_for_object offer as tags %}
            {% for tag in tags %}
                <a href="/tags/{{ tag }}">{{ tag }}</a>
            {% endfor %}</p>
			{% if offer.is_changeable %}
				{% ifequal offer.offerer request.user %}
					<form style="display: inline;" action="{% url offer_edit offer.id %}" method="GET">
						<input type="hidden" name="returnto" value="offer_list_yours" />
						<input type="submit" value="{% trans "Edit Offer" %}" />
					</form>
					{% if offer.is_deletable %}
						<form style="display: inline;" action="{% url offer_delete offer.id %}" method="POST">
							<input type="submit" value="{% trans "Delete Offer" %}" />
						</form>
					{% else %}
						{% if offer.is_cancelable %}
							<form style="display: inline;" action="{% url offer_cancel offer.id %}" method="POST">
								<input type="submit" value="{% trans "Cancel Offer" %}" />
							</form>
						{% endif %}
					{% endif %}
				{% endifequal %}
			{% endif %}
        </div>

    </div>

{% endblock %}

swaps/templates/swaps/propose_swap.html
{% extends "swaps/base.html" %}

{% load i18n %}

{% block head_title %}{% blocktrans %}Propose a Swap{% endblocktrans %}{% endblock %}

{% block body %}
    
    <h1>{% trans "Propose a Swap" %}</h1>
    
    <form id="proposal_form" method="POST" action="">
		<div>
			<h3>For: {{ offer.short_description }}</h3>
			<p>
				Offer: {{ offer.offering }}
			</p>
			<p>
				Want: {{ offer.want|urlize }}
			</p>
			<p>
				Offered by: {{ offer.offerer }}
			</p>
		</div>
		<div>
			<h3>
				Swap for one of your existing offers:
				{{ swap_form.proposing_offer }}
			</h3>
		</div>
        <div>
			<h3>Or make a new offer:</h3>
			<table>
				{{ offer_form }}
			</table>
        </div>
		<p><input type="submit" value="propose"/></p>
    </form>

{% endblock %}

swaps/templates/swaps/proposed_by_you.html
{% extends "swaps/base.html" %}

{% load i18n %}
{% load pagination_tags %}
{% load shorttimesince_tag %}

{% block head_title %}{% blocktrans %}Swaps proposed by you{% endblocktrans %}{% endblock %}

{% block body %}
    
    <h1>{% trans "Swaps proposed by you" %}</h1>  
    
    {% if swaps %}
    
        {% autopaginate swaps %}

			<table class="tasks" >
				<tr>
					<th>Proposal Time</th>
					<th>Your Offer</th>
					<th>Responding Offer</th>
					<th>Offered By</th>
					<th>State</th>
				</tr>
				{% for swap in swaps %}
					<tr class="{% cycle odd,even %}">
						<td><a href="{{ swap.get_absolute_url }}">{{ swap.proposed_time|shorttimesince }}</a></td>
						<td>{{ swap.proposing_offer }}</td>
						<td>{{ swap.responding_offer }}</td>
						<td>{{ swap.responding_offer.offerer }}</td>
						<td>{{ swap.get_state_display }}</td>
						<td>
							<form action="{% url cancel_swap swap.id %}" method="POST">
								<input type="submit" value="{% trans "Cancel" %}" />
							</form>
						</td>
					</tr>
				{% endfor %}
			</table>

        {% paginate %}

    {% else %}
        No proposed swaps.
    {% endif %}
    
{% endblock %}

swaps/templates/swaps/proposed_to_you.html
{% extends "swaps/base.html" %}

{% load i18n %}
{% load pagination_tags %}
{% load shorttimesince_tag %}

{% block head_title %}{% blocktrans %}Swaps proposed to you{% endblocktrans %}{% endblock %}

{% block body %}
    
    <h1>{% trans "Swaps proposed to you" %}</h1>
    
    
    {% if swaps %}

        
        {% autopaginate swaps %}

			<table class="tasks" >
				<tr>
					<th>Proposal Time</th>
					<th>Proposing Offer</th>
					<th>Offered By</th>
					<th>Your Offer</th>
					<th>State</th>
				</tr>
				{% for swap in swaps %}
					<tr class="{% cycle odd,even %}">
						<td><a href="{{ swap.get_absolute_url }}">{{ swap.proposed_time|shorttimesince }}</a></td>
						<td>{{ swap.proposing_offer }}</td>
						<td>{{ swap.proposing_offer.offerer }}</td>
						<td>{{ swap.responding_offer }}</td>
						<td>{{ swap.get_state_display }}</td>
						<td>
							<form style="display: inline;" action="{% url accept_swap swap.id %}" method="POST">
								<input type="submit" value="{% trans "Accept" %}" />
							</form>
							<form style="display: inline;" action="{% url reject_swap swap.id %}" method="POST">
								<input type="submit" value="{% trans "Reject" %}" />
							</form>
						</td>
					</tr>
				{% endfor %}
			</table>

        {% paginate %}

    {% else %}
        No proposed swaps.
    {% endif %}
    
{% endblock %}

swaps/templates/swaps/swap.html
{% extends "swaps/base.html" %}

{% load i18n %}
{% load tagging_tags %}
{% load comments_tag %}

{% block head_title %}{% blocktrans %}Swap{% endblocktrans %} : {{ swap }}{% endblock %}


{% block body %}

	<h1>{{ swap.get_state_display }} {% blocktrans %}Swap{% endblocktrans %}</h1>

    <h2>Proposing Offer:</h2>
    <div class="blog-post">
        <h3>{{ swap.proposing_offer.short_description }}</h3>
        <div class="blog-meta"><p>Offered by: <a href="{% url profiles.views.profile swap.proposing_offer.offerer.username %}">{{ swap.proposing_offer.offerer.username }}</a> on {{ swap.proposing_offer.offered_time|date }}</p></div>
        <p>
			Offering: {{ swap.proposing_offer.offering|urlize }}
		</p>
		<p>
			Want: {{ swap.proposing_offer.want|urlize }}
		</p>
		<div>
			{% ifequal swap.state "1" %}
				{% ifequal swap.proposing_offer.offerer request.user %}
					<form action="{% url offer_edit swap.proposing_offer.id %}" method="GET">
						<input type="hidden" name="returnto" value="proposed_by_you" />
						<input type="submit" value="{% trans "Edit Offer" %}" />
					</form>
			    {% endifequal %}
            {% endifequal %}
		</div>

    </div>
    <h2>Responding Offer:</h2>
    <div class="blog-post">
        <h3>{{ swap.responding_offer.short_description }}</h3>
        <div class="blog-meta"><p>Offered by: <a href="{% url profiles.views.profile swap.responding_offer.offerer.username %}">{{ swap.responding_offer.offerer.username }}</a> on {{ swap.responding_offer.offered_time|date }}</p></div>
        <p>
			Offering: {{ swap.responding_offer.offering|urlize }}
		</p>
		<p>
			Want: {{ swap.responding_offer.want|urlize }}
		</p>
		<div>
			{% ifequal swap.state "1" %}
				{% ifequal swap.responding_offer.offerer request.user %}
					<form action="{% url offer_edit swap.responding_offer.id %}" method="GET">
						<input type="hidden" name="returnto" value="proposed_to_you" />
						<input type="submit" value="{% trans "Edit Offer" %}" />
					</form>
			    {% endifequal %}
            {% endifequal %}
		</div>
    </div>

    <h2>Discussion of this Swap:</h2>
    {% comments swap %}
{% endblock %}

swaps/templates/swaps/your_offers.html
{% extends "swaps/base.html" %}

{% load i18n %}
{% load pagination_tags %}
{% load shorttimesince_tag %}

{% block head_title %}{% blocktrans %}Your Offers{% endblocktrans %}{% endblock %}

{% block body %}
    
    <h1>{% trans "Your Offers" %}</h1>
    
    
    {% if offers %}

        
        {% autopaginate offers %}

			<table class="tasks" >
				<tr>
					<th>Description</th>
					<th>Offer Time</th>
					<th>Offering</th>
					<th>Want</th>
					<th>State</th>
					<th>Swap</th>
				</tr>
				{% for offer in offers %}
					<tr class="{% cycle odd,even %}">
						<td><a href="{{ offer.get_absolute_url }}">{{ offer.short_description }}</a></td>
						<td>{{ offer.offered_time|shorttimesince }}</td>
						<td>{{ offer.offering|urlize }}</td>
						<td>{{ offer.want|urlize }}</td>
						<td>{{ offer.get_state_display }}</td>
						<td>
							{% if offer.swapped_by %}
								<a href="{{ offer.swapped_by.get_absolute_url }}">{{ offer.swapped_by }}</a>
							{% else %}
								{% if offer.proposed_swap %}
									<a href="{{ offer.proposed_swap.get_absolute_url }}">{{ offer.proposed_swap }}</a>
								{% else %}
									&nbsp;
								{% endif %}
							{% endif %}
						</td>
					</tr>
				{% endfor %}
			</table>

        {% paginate %}

    {% else %}
        No offers yet.
    {% endif %}
    
{% endblock %}